window.PORTFOLIO_CONTENT={
  panels:{
    projects:{number:'01',label:'SELECTED WORK',title:'用结构化研究理解企业与市场。',sections:[
      {eyebrow:'01 / ALTERNATIVE ASSETS · MARKET RESEARCH',title:'Nucleus Cards',text:'围绕收藏卡市场信息分散、交易与挂牌口径混杂且样本有限。我独立开展需求研究、产品定义与数据方案设计，构建可追溯的比较框架，并交付线上研究产品。',bullets:['围绕信息来源、价格口径与样本质量组织研究流程。','区分市场信号和信息不确定性，保留证据来源。','在样本不足时明确限制，避免把观察误当成结论。'],tags:['Next.js','React','TypeScript','Supabase','AI SDK','Vercel'],links:[['在线演示','https://nucleus-cards.vercel.app/'],['GitHub 仓库','https://github.com/gfthcode/nucleus-cards']]},
      {eyebrow:'02 / DATA · ANALYTICS · NBA',title:'CourtMatch Analytics',text:'针对公开数据分散、指标定义不一的问题，标准化多源数据并建立质量校验与方法说明，让球队与球员表现可以在统一口径下比较。',bullets:['处理 CSV、Excel 与 Parquet 数据，建立标准化流程。','加入 Schema 与关系校验，保留来源、时间与方法说明。','独立完成需求定义、数据方案、产品实现与公开部署。'],tags:['Python','Pandas','JSON','GitHub Pages'],links:[['在线演示','https://gfthcode.github.io/courtmatch-analytics/'],['GitHub 仓库','https://github.com/gfthcode/courtmatch-analytics']]}
    ]},
    experience:{number:'02',label:'FIELD NOTES / EXPERIENCE',title:'Rokid · 产品与市场研究',sections:[{eyebrow:'杭州 · 2025.12 — 2026.02',title:'研究科技产品如何形成用户价值与市场适配。',text:'在 Rokid 参与智能眼镜产品、用户需求、竞品与海外市场研究。',subsections:[['Agent 链路与端云协同','梳理用户从需求提出到产品反馈的关键链路，归类 70+ 条用户意图，并整理平台适配范围、功能边界与交互要求，为团队评估产品需求和实现优先级提供依据。'],['无障碍体验','基于近 200 位视障、听障用户反馈，参与 OCR、TTS 和读屏体验优化。项目指标：首包延迟从 9 秒以上降至 1 秒以内，OCR 错误率约从 25% 降到 10% 以下，核心读屏标签覆盖率从低于 30% 提升至 100%。'],['国际化适配','对照国际智能眼镜及多语言交互产品，研究功能定位、语言覆盖、在线与离线限制，支持 9+ 新增语言的市场适配范围与风险评估。']],tags:['AIUI Agent','用户研究','OCR / TTS','无障碍','端云协同','多语言']}]},
    github:{number:'03',label:'OPEN SOURCE / GITHUB',title:'在项目中练习行业研究与数据判断。',sections:[{eyebrow:'GITHUB.COM / GFTHCODE',title:'可查看的项目与代码',text:'下面列出简历与现有网站中的真实仓库入口。',repos:[['nucleus-cards','另类资产研究产品 · Next.js / Supabase / AI SDK','https://github.com/gfthcode/nucleus-cards'],['courtmatch-analytics','NBA 数据分析项目 · Python / Pandas','https://github.com/gfthcode/courtmatch-analytics']],links:[['打开 GitHub 个人主页','https://github.com/gfthcode']]}]},
    about:{number:'04',label:'THE PERSON / ABOUT ME',title:'陈高波 CHEN GAOBO',sections:[{eyebrow:'UNSW · SYDNEY · FINTECH',title:'在金融、技术和商业之间建立连接。',text:'新南威尔士大学金融科技本科生（2025—2027），关注投资银行、股权资本市场与科技企业融资。具备产品与用户研究、数据分析和从 0 到 1 项目实践，期待将技术理解与结构化分析用于行业研究、企业分析和交易支持工作。',subsections:[['教育背景','新南威尔士大学（University of New South Wales）｜金融科技本科｜2025—2027'],['技能','行业与公司研究、商业分析、用户研究、数据分析、Excel、Python、SQL、Pandas'],['兴趣','股权资本市场、科技企业、商业研究'],['联系方式','电话：15268817047｜邮箱：g1628908@gmail.com']],links:[['拨打电话','tel:+8615268817047'],['发送邮件','mailto:g1628908@gmail.com'],['在线查看简历 PDF','assets/Chen_Gaobo_Resume.pdf']] }]}
  }
};
