window.PORTFOLIO_CONTENT={
  panels:{
    projects:{number:'01',label:'SELECTED WORK',title:'把想法做成可用的产品。',sections:[
      {eyebrow:'01 / PRODUCT · DATA · AI',title:'Nucleus Cards',text:'围绕另类资产信息分散、挂牌与成交口径容易混淆、样本稀少的问题，设计一套可追溯的研究流程。项目从需求定义到前后端集成与线上 MVP，由我独立推进。',bullets:['让发现、比较与复盘形成连续的产品流程。','将证据来源和数据口径保留在研究结果中。','样本不足时降低结论强度；AI 输出附带证据、置信度与失效条件。'],tags:['Next.js','React','TypeScript','Supabase','AI SDK','Vercel'],links:[['在线演示','https://nucleus-cards.vercel.app/'],['GitHub 仓库','https://github.com/gfthcode/nucleus-cards']]},
      {eyebrow:'02 / DATA · ANALYTICS · NBA',title:'CourtMatch Analytics',text:'把多源篮球数据整理成可重复使用的研究流程，从清洗、ID 映射到比赛分析看板，明确口径并降低数据质量问题。',bullets:['制定 CSV、Excel、Parquet 数据清洗标准。','加入 Schema 与外键校验、更新时间和方法说明。','将分析流程部署到 GitHub Pages。'],tags:['Python','Pandas','JSON','GitHub Pages'],links:[['在线演示','https://gfthcode.github.io/courtmatch-analytics/'],['GitHub 仓库','https://github.com/gfthcode/courtmatch-analytics']]}
    ]},
    experience:{number:'02',label:'FIELD NOTES / EXPERIENCE',title:'Rokid AIUI · AI 产品实习生',sections:[{eyebrow:'杭州 · 2025.12 — 2026.02',title:'让 AI 眼镜里的体验更自然，也更包容。',text:'参与 Rokid AI 眼镜 AIUI Agent 交互链路、无障碍体验与海外多语言适配。',subsections:[['Agent 链路与端云协同','沿着“用户请求→请求路由→意图识别→AIUI Agent→眼镜端卡片渲染→动作回传”梳理端到端链路，明确关键节点与端云衔接关系；整理 70+ 条意图，并对应梳理眼镜端呈现、用户动作回传等跨端交互边界，沉淀为流程说明与意图清单，便于产品、算法与客户端对齐方案和实现范围。'],['无障碍体验','基于近 200 位视障、听障用户反馈，参与 OCR、TTS 和读屏体验优化。项目指标：首包延迟从 9 秒以上降至 1 秒以内，OCR 错误率约从 25% 降到 10% 以下，核心读屏标签覆盖率从低于 30% 提升至 100%。'],['国际化适配','拆解界面、语音识别、意图、语音播报与 OTA 文案的适配边界，支持 9+ 新增语言的范围与风险评估。']],tags:['AIUI Agent','用户研究','OCR / TTS','无障碍','端云协同','多语言']}]},
    github:{number:'03',label:'OPEN SOURCE / GITHUB',title:'在公开仓库里持续迭代。',sections:[{eyebrow:'GITHUB.COM / GFTHCODE',title:'可查看的项目与代码',text:'下面列出简历与现有网站中的真实仓库入口。',repos:[['nucleus-cards','另类资产研究产品 · Next.js / Supabase / AI SDK','https://github.com/gfthcode/nucleus-cards'],['courtmatch-analytics','NBA 数据分析项目 · Python / Pandas','https://github.com/gfthcode/courtmatch-analytics']],links:[['打开 GitHub 个人主页','https://github.com/gfthcode']]}]},
    about:{number:'04',label:'THE PERSON / ABOUT ME',title:'陈高波 CHEN GAOBO',sections:[{eyebrow:'UNSW · SYDNEY · FINTECH',title:'在金融、技术和产品之间找问题。',text:'新南威尔士大学金融科技本科生（2025—2027）。关注 AI 产品、数据与真实用户体验，喜欢从用户反馈出发，把复杂需求拆解成可交付的方案。',subsections:[['教育背景','University of New South Wales｜金融科技本科｜2025—2027'],['技能','产品需求分析、用户研究、AI 产品设计、数据分析、Python、Pandas、Next.js、React、TypeScript、Supabase'],['兴趣','NBA、攀岩、卡丁车'],['联系方式','电话：15268817047｜邮箱：g1628908@gmail.com']],links:[['拨打电话','tel:+8615268817047'],['发送邮件','mailto:g1628908@gmail.com'],['在线查看简历 PDF','assets/Chen_Gaobo_Resume.pdf']] }]}
  }
};
